//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrains.Debugger.Worker.Plugins.Unity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrains.Debugger.Worker.Plugins.Unity.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUnable to pause Unity editor. Exception occured: &apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string UnityPausePointExceptionOccured {
            get {
                return ResourceManager.GetString("UnityPausePointExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity pausepoint hit. Pausing Unity editor at the end of frame.
        /// </summary>
        internal static string UnityPausePointHit {
            get {
                return ResourceManager.GetString("UnityPausePointHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occurred, cannot load assembly to read texture data:&apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string UnityTextureDebuggingCannotLoadDllLabel {
            get {
                return ResourceManager.GetString("UnityTextureDebuggingCannotLoadDllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occurred, cannot find required method to read texture data:&apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string UnityTextureDubuggingCannotFindRequiredMethod {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotFindRequiredMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occurred, cannot find required type to read texture data:&apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string UnityTextureDubuggingCannotFindRequiredType {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotFindRequiredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occurred, cannot get texture debug information:&apos;&apos;{0}&apos;&apos;.
        /// </summary>
        internal static string UnityTextureDubuggingCannotGetTextureInfo {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotGetTextureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occurred, cannot parse texture information.
        /// </summary>
        internal static string UnityTextureDubuggingCannotParseTextureInfo {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotParseTextureInfo", resourceCulture);
            }
        }
    }
}
