//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrains.Debugger.Worker.Plugins.Unity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JetBrains.Debugger.Worker.Plugins.Unity.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnityTextureDebuggingCannotLoadDllLabel {
            get {
                return ResourceManager.GetString("UnityTextureDebuggingCannotLoadDllLabel", resourceCulture);
            }
        }
        
        internal static string UnityTextureDubuggingCannotFindRequiredType {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotFindRequiredType", resourceCulture);
            }
        }
        
        internal static string UnityTextureDubuggingCannotFindRequiredMethod {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotFindRequiredMethod", resourceCulture);
            }
        }
        
        internal static string UnityTextureDubuggingCannotGetTextureInfo {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotGetTextureInfo", resourceCulture);
            }
        }
        
        internal static string UnityTextureDubuggingCannotParseTextureInfo {
            get {
                return ResourceManager.GetString("UnityTextureDubuggingCannotParseTextureInfo", resourceCulture);
            }
        }
    }
}
