// <auto-generated/>

global using TestAttribute = JetBrains.TestFramework.TestAttribute;
global using TestCaseAttribute = JetBrains.TestFramework.TestCaseAttribute;
global using TestCaseSourceAttribute = JetBrains.TestFramework.TestCaseSourceAttribute;
global using TestFixtureAttribute = JetBrains.TestFramework.TestFixtureAttribute;
global using TestFixtureSourceAttribute = JetBrains.TestFramework.TestFixtureSourceAttribute;
global using SetUpFixtureAttribute = JetBrains.TestFramework.SetUpFixtureAttribute;
global using ExplicitAttribute = JetBrains.TestFramework.ExplicitAttribute;
global using CategoryAttribute = JetBrains.TestFramework.CategoryAttribute;
global using IgnoreAttribute = JetBrains.TestFramework.IgnoreAttribute;