package com.jetbrains.rider.plugins.unity.spellchecker

import com.intellij.rider.rdclient.dotnet.spellchecker.strategy.BackendLanguageSpellcheckingStrategy
import com.jetbrains.rider.plugins.unity.ideaInterop.fileTypes.shaderLab.ShaderLabLanguage

class ShaderLabSpellcheckingStrategy : BackendLanguageSpellcheckingStrategy(ShaderLabLanguage)