#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using JetBrains.Application;
using JetBrains.Application.Parts;
using JetBrains.HabitatDetector;
using JetBrains.ProjectModel;
using JetBrains.ProjectModel.BuildTools;
using JetBrains.ProjectModel.MSBuild.BuildTools;
using JetBrains.ReSharper.Plugins.Unity.UnityEditorIntegration;
using JetBrains.Util;

namespace JetBrains.ReSharper.Plugins.Unity.Core.ProjectModel.Runtime;

[ShellComponent(Instantiation.DemandAnyThreadSafe)]
public class UnityBuildToolSelector(SolutionsManager solutionsManager) : IBuildToolSelector
{
    private const int MinUnityMajorVersionToAvoidMonoDefault = 2022;
    private const int MinMacOsMajorVersionToAvoidMonoDefault = 27;

    public IBuildTool? Select(VirtualFileSystemPath solutionFilePath,
        IReadOnlyCollection<VirtualFileSystemPath> projectFiles,
        IReadOnlyCollection<IBuildTool> buildTools)
    {
        var solution = solutionsManager.Solution;
        if (solution == null)
            return null;

        var unityVersion = solution.TryGetComponent<UnityVersion>();
        if (unityVersion == null)
            return null;
            
        var appPath = unityVersion.ActualAppPathForSolution.Maybe.ValueOrDefault;
        var contentPath = UnityInstallationFinder.GetApplicationContentsPath(appPath);

        if (!contentPath.IsEmpty)
        {
            // when we have Unity build tool, we should use it
            var unityBuildTool = buildTools.FirstOrDefault(buildTool => buildTool.Directory.StartsWith(contentPath));
            if (unityBuildTool != null)
                return unityBuildTool;
        }

        if (ShouldAvoidMonoDefault(unityVersion.ActualVersionForSolution.Value))
            return SelectBestNonMonoBuildTool(buildTools);

        return null;
    }

    // Starting with macOS 27, Rosetta 2 is no longer installed by default, so mono msbuild would fail to launch at all.
    // Rosetta can still be installed manually, but we currently have no reliable way to detect whether it's present.
    // Since evaluating csproj files generated by Unity 2022+ is safe with dotnet core msbuild, we prefer it over mono msbuild in this case.
    private static bool ShouldAvoidMonoDefault(Version unityVersion)
    {
        return unityVersion.Major >= MinUnityMajorVersionToAvoidMonoDefault 
               && PlatformUtil.RuntimePlatform == JetPlatform.MacOsX
               && Environment.OSVersion.Version.Major >= MinMacOsMajorVersionToAvoidMonoDefault;
    }
    
    private static IBuildTool? SelectBestNonMonoBuildTool(IReadOnlyCollection<IBuildTool> buildTools)
    {
        var nonMonoBuildTools = buildTools.Where(buildTool => buildTool is not MonoMsBuildTool).ToList();
        return BuildToolContainer.GetHighest(nonMonoBuildTools);
    }
}