//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Windows.Markup.XmlnsDefinitionAttribute("urn:shemas-jetbrains-com:ui-application-icons-insight-unity-icons", "JetBrains.ReSharper.Plugins.Unity.Resources.Icons")]

namespace JetBrains.ReSharper.Plugins.Unity.Resources.Icons
{
    public sealed class InsightUnityIcons
    {

        #region InsightHot

        /// <summary>
        ///	<para>
        ///		<para>InsightHot Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="InsightHot"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:XedymylThemedIconsThemedIcons+InsightHot}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(XedymylThemedIconsThemedIcons.InsightHot))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = XedymylThemedIconsThemedIcons.InsightHot.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;XedymylThemedIconsThemedIcons.InsightHot&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class InsightHot : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="InsightHot">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id =
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightHot));

            /// <summary>Loads the image for Themed Icon InsightHot theme aspect Default.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Default()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M11.044,3.626C10.887,4.7,10.966,6.042,8.8,7.079C9.483,4.39,8.686,1.765,7.2,1C7.745,4.716,4,6.459,4,10.044C4,12.982,5.586,14,7.109,14C11.79,14,12,8.88,12,7.364C12.078814212615221,6.0489985204878778,11.744469886498315,4.741698216068424,11.044,3.6259999999999994ZM11.044,3.626M9.6390000000000011,11.266C9.4470106290940681,11.75218012429189,9.1258854429763012,12.176844431590656,8.7103927132138228,12.494014454310106C8.2948999834513444,12.811184477029556,7.8005963013697919,13.008984954615764,7.2810000000000006,13.066C6.586,13.066,5.421,12.766,5.421,10.757000000000001C5.421,8.9720000000000013,6.814,7.088000000000001,7.509,6.019000000000001C7.8378401335391761,7.3977063724002683,7.7824930058539081,8.8405368072455968,7.3489999999999993,10.190000000000001C8.5131815084529574,9.7766849409366952,9.4846989935026826,8.9476709373757437,10.075999999999999,7.8630000000000013C10.168543117696277,9.01534579678098,10.019698547511446,10.174426053849576,9.6389999999999958,11.266ZM9.6390000000000011,11.266' fill='#9AA7B0'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon InsightHot.</summary>
            public override
                global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                GetThemeImages()
            {
                return new
                    global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                    {
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage("Default",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(this.Load_Default))
                    };
            }
        }

        #endregion


        #region InsightUnity

        /// <summary>
        ///	<para>
        ///		<para>InsightUnity Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="InsightUnity"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:XedymylThemedIconsThemedIcons+InsightUnity}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(XedymylThemedIconsThemedIcons.InsightUnity))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = XedymylThemedIconsThemedIcons.InsightUnity.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;XedymylThemedIconsThemedIcons.InsightUnity&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class InsightUnity : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="InsightUnity">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id =
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightUnity));

            /// <summary>Loads the image for Themed Icon InsightUnity theme aspect Default.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Default()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M13,6.684L11.812,2L7.38,3.255L6.661,4.571L5.245,4.571L2,8L5.245,11.429L6.661,11.429L7.38,12.745000000000001L11.812,14L13,9.316L12.281,8ZM13,6.684M6.8,4.752L10.126,3.8099999999999996L8.183,7.357L4.329,7.357ZM6.8,4.752M6.8,11.251999999999999L4.334,8.652L8.183,8.652L10.121,12.199ZM6.8,11.251999999999999M11.18,11.552L9.237,8L11.175,4.4529999999999994L12.074,8ZM11.18,11.552' fill='#9AA7B0'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon InsightUnity.</summary>
            public override
                global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                GetThemeImages()
            {
                return new
                    global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                    {
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage("Default",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(this.Load_Default))
                    };
            }
        }

        #endregion

    }
}
