//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Windows.Markup.XmlnsDefinitionAttribute("urn:shemas-jetbrains-com:ui-application-icons-divebom-themed-icons", "JetBrains.UI.ThemedIcons")]

namespace JetBrains.UI.ThemedIcons
{
	
	
	/// <summary>
	///	<para>
	///		<para>Autogenerated identifier classes and identifier objects to Themed Icons registered with <see cref="JetBrains.Application.Icons.IThemedIconManager"></see>.</para>
	///		<para>Identifier classes should be used in attributes, XAML, or generic parameters. Where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected, use the identifier object in the <c>Id</c> field of the identifier class.</para>
	///	</para>
	///</summary>
	///<remarks>
	///	<para>This code was compile-time generated to support Themed Icons in the JetBrains application.</para>
	///	<para>It has two primary goals: load the icons of this assembly to be registered with <see cref="JetBrains.Application.Icons.IThemedIconManager"></see> so that they were WPF-accessible and theme-sensitive; and emit early-bound accessors for referencing icons in codebehind in a compile-time-validated manner.</para>
	///	<h1>XAML</h1>
	///	<para>For performance reasons, the icons are not individually exposed with application resources. There is a custom markup extension to bind an image source in markup.</para>
	///	<para>To use an icon from XAML, set an <see cref="System.Windows.Media.ImageSource"></see> property to the <see cref="System.CodeDom.CodeTypeReference"></see> markup extension, which takes an icon identifier class (nested in <see cref="JetBrains.UI.ThemedIcons.DivebomThemedIconsThemedIcons"></see> class) as a parameter.</para>
	///	<para>Example:</para>
	///	<code>&lt;Image Source="{icons:ThemedIcon myres:DivebomThemedIconsThemedIcons+Trinity}" /&gt;</code>
	///	<h1>Attributes</h1>
	///	<para>Sometimes you have to reference an icon from a type attriute when you're defining objects in code. Typical examples are Options pages and Tool Windows.</para>
	///	<para>To avoid the use of string IDs which are not validated very well, we've emitted identifier classes to be used with <c>typeof()</c> expression, one per each icon. Use the attribute overload which takes a <see cref="System.Type"></see> for an image, and choose your icon class from nested classes in the <see cref="JetBrains.UI.ThemedIcons.DivebomThemedIconsThemedIcons"></see> class.</para>
	///	<para>Example:</para>
	///	<code>[Item(Name="Sample", Icon=typeof(DivebomThemedIconsThemedIcons.Trinity))]</code>
	///	<h1>CodeBehind</h1>
	///	<para>In codebehind, we have two distinct tasks: (a) specify some icon in the APIs and (b) render icon images onscreen.</para>
	///	<para>On the APIs stage you should only manipulate icon identifier objects (of type <see cref="JetBrains.UI.Icons.IconId"></see>, statically defined in <see cref="JetBrains.UI.ThemedIcons.DivebomThemedIconsThemedIcons"></see> in <c>Id</c> fields). Icon identifier classes (nested in <see cref="JetBrains.UI.ThemedIcons.DivebomThemedIconsThemedIcons"></see>) should be turned into icon identifier objects as early as possible. Rendering is about getting an <see cref="System.Windows.Media.ImageSource"></see> to assign to WPF, or <see cref="System.Drawing.Bitmap"></see> to use with GDI+ / Windows Forms.</para>
	///	<para>You should turn an identifier object into a rendered image as late as possible. The identifier is static and lightweight and does not depend on the current theme, while the image is themed and has to be loaded or generated/rasterized. You need an <see cref="JetBrains.Application.Icons.IThemedIconManager"></see> instance to get the image out of an icon identifier object. Once you got the image, you should take care to change it with theme changes — either by using a live image property, or by listening to the theme change event. See <see cref="JetBrains.Application.Icons.IThemedIconManager"></see> and its extensions for the related facilities.</para>
	///	<para>Example:</para>
	///	<code>// Getting IconId identifier object to use with APIs
	///IconId iconid = DivebomThemedIconsThemedIcons.Trinity.Id;</code>
	///	<code>// Getting IconId out of an Icon Identifier Class type
	///IconId iconid = new JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(DivebomThemedIconsThemedIcons.Trinity));</code>
	///	<code>// Getting image for screen rendering by IconId
	///themediconmanager.Icons[icnoid]</code>
	///	<code>// Getting image for screen rendering by Icon Identifier Class
	///themediconmanager.GetIcon&lt;DivebomThemedIconsThemedIcons.Trinity&gt;()</code>
	///	<h1>Icons Origin</h1>
	///	<para>This code was generated by a pre-compile build task from a set of input files which are XAML files adhering to a certain convention, as convenient for exporting them from the Illustrator workspace, plus separate PNG files with raster icons. In the projects, these files are designated with <c>ThemedIconsXamlV3</c> and <c>ThemedIconPng</c> build actions and do not themselves get into the output assembly. All of such files are processed, vector images for different themes of the same icon are split and combined into the single list of icons in this assembly. This list is then written into the genearted XAML file (compiled into BAML within assembly), and serves as the source for this generated code.</para>
	///</remarks>
	public sealed class DivebomThemedIconsThemedIcons
	{
		
		#region Shader
		/// <summary>
		///	<para>
		///		<para>Shader Themed Icon generated identifiers:</para>
		///		<para>— <see cref="Shader"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
		///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
		///		<para>
		///			<code>
		///                                 
		///           _=*?Foj[sc+"          
		///        _\j?_'_"=`-_,=|pI=       
		///      =5T'`  +Vh4 ``^Vr:~58l`    
		///    `1e'    *h4GA````=80O;^88'   
		///    fS_+aPV7  ```R##80\---``WM-  
		///   ;P"^PVh4,`````#80MMw-...`_ga  
		///   {V.Ih4GA'`````0MM%$N..''' gg  
		///   54   ```k##80M---...ggggg gg  
		///   Lw_ ````o80MM%-...'"gggg5"gR  
		///   `kh`````;MM%$N..'''5gg@D.0g_  
		///    .Gw_+#MM;-...gggg#_'_`-W@~   
		///     `v8s~;xM+.''ggg8_'-_F@8'    
		///       -\kMF=;"'`7+,'_TgNI'      
		///          -L5h#$gggMRVF'         
		///                                 
		///</code>
		///		</para>
		///	</para>
		///</summary>
		///<remarks>
		///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
		///</remarks>
		///<example>
		///	<code>&lt;Image Source="{icons:ThemedIcon myres:DivebomThemedIconsThemedIcons+Shader}" /&gt;        &lt;!-- XAML --&gt;</code>
		///</example>
		///<example>
		///	<code>[Item(Name="Sample", Icon=typeof(DivebomThemedIconsThemedIcons.Shader))]        // C# Type attribute</code>
		///</example>
		///<example>
		///	<code>IconId iconid = DivebomThemedIconsThemedIcons.Shader.Id;        // IconId identifier object</code>
		///</example>
		///<example>
		///	<code>themediconmanager.GetIcon&lt;DivebomThemedIconsThemedIcons.Shader&gt;()        // Icon image for rendering</code>
		///</example>
		[global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
		public sealed class Shader : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
		{
			
			/// <inheritdoc cref="Shader">identifier class</inheritdoc>
			public static global::JetBrains.UI.Icons.IconId Id = new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(Shader));
			
			/// <summary>Loads the image for Themed Icon Shader theme aspect Color.</summary>
			public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Color()
			{
				return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromCanonicalSExpressionAsciiString("(7:TiImage2:v1(6:Vector(4:Size5:16,16)(7:Drawing(4:Path(4:Fill(5:Solid9:#00FFFFFF" +
						"))(8:Segments(1:F2:161:81:11:1)(1:C1:82:162:1618:12.41827799864634918:12.4182779" +
						"986463492:16)(1:C0:1:818:3.58172200135365152:160:18:12.418277998646349)(1:C1:80:" +
						"0:18:3.581722001353651518:3.58172200135365150:)(1:C2:161:818:12.4182779986463490" +
						":2:1618:3.5817220013536515)))(4:Path(4:Fill(6:Linear(5:Start35:0.146446428571429" +
						",0.146446428571429)(3:End35:0.853553571428571,0.853553571428571)(5:Stops9:#FF4E6" +
						"EA10:9:#FF11003B1:1)))(8:Segments(1:F2:151:81:11:1)(1:C1:82:152:1518:11.86599324" +
						"881555418:11.8659932488155542:15)(1:C1:11:818:4.13400675118444562:151:118:11.865" +
						"993248815554)(1:C1:81:11:118:4.134006751184445618:4.13400675118444561:1)(1:C2:15" +
						"1:818:11.8659932488155541:12:1518:4.1340067511844456)))(4:Path(4:Fill(6:Linear(5" +
						":Start35:0.146446666666667,0.146446666666667)(3:End35:0.853553333333333,0.853553" +
						"333333333)(5:Stops9:#FFFFFFFF0:9:#FFFFC3701:1)))(8:Segments(1:F2:141:81:11:1)(1:" +
						"C1:82:142:1418:11.31370849898476118:11.3137084989847612:14)(1:C1:21:818:4.686291" +
						"50101523882:141:218:11.313708498984761)(1:C1:81:21:218:4.686291501015238818:4.68" +
						"629150101523881:2)(1:C2:141:818:11.3137084989847611:22:1418:4.6862915010152388))" +
						")(4:Path(4:Fill(6:Linear(5:Start35:0.158719167091593,0.158719166666667)(3:End35:" +
						"0.841280832833681,0.841280833333333)(5:Stops9:#FF4E6EA10:9:#FF11003B1:1)))(8:Seg" +
						"ments(1:F1:82:141:11:1)(1:C18:5.002507923695814518:13.19577769292814316:6.947629" +
						"5615990718:13.99979022284731318:5.913649429685886418:13.722375015071698)(1:C18:2" +
						".80927000000000062:1118:4.091366417705742718:12.66918037078458818:3.334812478635" +
						"425418:11.911750342350555)(1:L6:5.40462:11)(1:C1:82:147:5.923528:12.791636:6.890" +
						"22:14)(1:F1:82:141:10:)(1:F2:111:81:11:1)(1:C18:10.5953999999999982:1118:11.0056" +
						"3843545252518:9.013965276604434318:10.86945138625597618:10.023755557349986)(1:L1" +
						"8:13.1907399999999982:11)(1:C2:141:818:13.72078583548442118:10.08913926908939718" +
						":14.00005651479703418:9.0538576069068615)(1:F2:111:81:10:)(1:F6:5.40461:51:11:1)" +
						"(1:L7:2.809271:5)(1:C1:218:7.999999999999996418:2.279220668244191617:5.910859754" +
						"59526318:1.999946521398786416:6.94614147829219)(1:L1:518:7.9999999999999964)(1:C" +
						"18:5.404600000000002118:5.000000000000005318:4.994361564547475918:6.986034723395" +
						"565718:5.130548613744025518:5.9762444426500139)(1:F6:5.40461:51:10:)(1:F18:10.59" +
						"54000000000021:51:11:1)(1:L18:13.1907400000000021:5)(1:C18:10.99749774696401718:" +
						"2.804219806241334818:12.66519667467219718:4.088248189550056618:11.90864115979243" +
						"618:3.3308172159527163)(1:C1:818:2.000000000000000918:10.08635433413559818:2.277" +
						"622396529952918:9.052372133507221417:2.000208021193536)(1:C7:10.59541:56:9.10981" +
						":28:10.076487:3.20837)(1:F18:10.5954000000000021:51:10:)(1:F18:10.59540000000000" +
						"22:111:11:1)(1:L1:82:11)(1:L1:82:14)(1:C7:10.59542:116:9.10982:148:10.076488:12." +
						"79163)(1:F18:10.5954000000000022:111:10:)(1:F1:51:81:11:1)(1:C6:5.404618:10.9999" +
						"9999999999818:4.994361564547472417:9.01396527660443618:5.130548613744021918:10.0" +
						"23755557349983)(1:L1:818:10.999999999999998)(1:L1:81:8)(1:F1:51:81:10:)(1:F1:81:" +
						"51:11:1)(1:L1:81:8)(1:L2:111:8)(1:C18:10.59539999999999818:5.000000000000000918:" +
						"11.00563843545252518:6.986034723395565718:10.86945138625597618:5.976244442650014" +
						"8)(1:F1:81:51:10:)(1:F6:5.40461:51:11:1)(1:L1:81:5)(1:L1:81:2)(1:C6:5.40461:56:6" +
						".89021:27:5.923527:3.20837)(1:F6:5.40461:51:10:)))(4:Path(4:Fill(6:Linear(5:Star" +
						"t35:0.146445833333333,0.146445833333333)(3:End35:0.853554166666667,0.85355416666" +
						"6667)(5:Stops9:#FFFFF3E20:9:#FFFFFFFF1:1)))(8:Segments(1:F1:81:21:11:1)(1:C18:3." +
						"757359312880715218:3.757359312880714318:6.40931135905218511:218:4.88214603765132" +
						"8818:2.6325725881101012)(1:C1:218:7.999999999999999118:2.632572588110101618:4.88" +
						"214603765132791:218:6.4093113590521842)(1:C18:3.757359312880715218:12.2426406871" +
						"1928618:1.999999999999999817:9.59068864094781418:2.632572588110101218:11.1178539" +
						"62348672)(1:C18:7.99999999999999912:1418:4.882146037651327916:13.367427411889918" +
						":6.40931135905218422:14)(1:C18:12.24264068711928418:12.24264068711928617:9.59068" +
						"86409478142:1417:11.1178539623486716:13.3674274118899)(1:C2:1418:8.0000000000000" +
						"01818:13.36742741188989818:11.1178539623486722:1418:9.5906886409478176)(1:C18:13" +
						".19615242270663218:5.00000000000000092:1418:6.946858429339694218:13.722723208036" +
						"78618:5.9120473539732714)(1:C2:1117:2.80384757729336818:12.66958163737647816:4.0" +
						"879526460267318:11.91204735397327118:3.3304183626235218)(1:C18:7.999999999999997" +
						"31:218:10.08795264602672918:2.277276791963214218:9.053141570660304918:1.99999999" +
						"99999996)(1:F1:81:21:10:)(1:F1:84:13.51:11:1)(1:C18:4.110912703473989218:11.8890" +
						"8729652601118:6.54186874579783684:13.518:5.141967201180384518:12.920141794232407" +
						")(1:C3:2.51:818:3.079858205767593818:10.8580327988196153:2.518:9.458131254202163" +
						"2)(1:C18:4.110912703473989218:4.11091270347398833:2.518:6.541868745797835118:3.0" +
						"79858205767592918:5.1419672011803836)(1:C18:7.99999999999999913:2.518:5.14196720" +
						"1180384518:3.079858205767592918:6.541868745797835918:2.5000000000000004)(1:C18:1" +
						"1.88908729652601118:4.110912703473987418:9.458131254202163218:2.4999999999999996" +
						"18:10.85803279881961518:3.0798582057675921)(1:C4:13.518:7.999999999999998218:12." +
						"92014179423240718:5.14196720118038284:13.518:6.5418687457978351)(1:C18:12.763139" +
						"7208144155:10.754:13.516:8.9653797731052818:13.24582960736705518:9.9139565921911" +
						"679)(1:C18:10.75000000000000218:12.76313972081441318:12.28044983426177518:11.586" +
						"04340780883218:11.58604340780883218:12.280449834261772)(1:C1:818:13.500000000000" +
						"00216:9.9139565921911718:13.24582960736705518:8.965379773105281618:13.5000000000" +
						"00002)(1:F1:84:13.51:10:))))(8:ClipMask)))");
			}
			
			/// <summary>Loads the image for Themed Icon Shader theme aspect Gray.</summary>
			public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Gray()
			{
				return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromCanonicalSExpressionAsciiString("(7:TiImage2:v1(6:Vector(4:Size5:16,16)(7:Drawing(4:Path(4:Fill(5:Solid9:#FFF4F4F4" +
						"))(8:Segments(1:F2:161:81:11:1)(1:C1:82:162:1618:12.41827799864634918:12.4182779" +
						"986463492:16)(1:C0:1:818:3.58172200135365152:160:18:12.418277998646349)(1:C1:80:" +
						"0:18:3.581722001353651518:3.58172200135365150:)(1:C2:161:818:12.4182779986463490" +
						":2:1618:3.5817220013536515)))(4:Path(4:Fill(5:Solid9:#FF323232))(8:Segments(1:F2" +
						":151:81:11:1)(1:C1:82:152:1518:11.86599324881555418:11.8659932488155542:15)(1:C1" +
						":11:818:4.13400675118444562:151:118:11.865993248815554)(1:C1:81:11:118:4.1340067" +
						"51184445618:4.13400675118444561:1)(1:C2:151:818:11.8659932488155541:12:1518:4.13" +
						"40067511844456)))(4:Path(4:Fill(5:Solid9:#FFEBEBEB))(8:Segments(1:F2:141:81:11:1" +
						")(1:C1:82:142:1418:11.31370849898476118:11.3137084989847612:14)(1:C1:21:818:4.68" +
						"629150101523882:141:218:11.313708498984761)(1:C1:81:21:218:4.686291501015238818:" +
						"4.68629150101523881:2)(1:C2:141:818:11.3137084989847611:22:1418:4.68629150101523" +
						"88)))(4:Path(4:Fill(5:Solid9:#FF323232))(8:Segments(1:F1:82:141:11:1)(1:C18:5.00" +
						"2507923695814518:13.19577769292814316:6.9476295615990718:13.99979022284731318:5." +
						"913649429685886418:13.722375015071698)(1:C18:2.80927000000000062:1118:4.09136641" +
						"7705742718:12.66918037078458818:3.334812478635425418:11.911750342350555)(1:L6:5." +
						"40462:11)(1:C1:82:147:5.923528:12.791636:6.89022:14)(1:F1:82:141:10:)(1:F2:111:8" +
						"1:11:1)(1:C18:10.5953999999999982:1118:11.00563843545252518:9.013965276604434318" +
						":10.86945138625597618:10.023755557349986)(1:L18:13.1907399999999982:11)(1:C2:141" +
						":818:13.72078583548442118:10.08913926908939718:14.00005651479703418:9.0538576069" +
						"068615)(1:F2:111:81:10:)(1:F6:5.40461:51:11:1)(1:L7:2.809271:5)(1:C1:218:7.99999" +
						"9999999996418:2.279220668244191617:5.91085975459526318:1.999946521398786416:6.94" +
						"614147829219)(1:L1:518:7.9999999999999964)(1:C18:5.404600000000002118:5.00000000" +
						"0000005318:4.994361564547475918:6.986034723395565718:5.130548613744025518:5.9762" +
						"444426500139)(1:F6:5.40461:51:10:)(1:F18:10.5954000000000021:51:11:1)(1:L18:13.1" +
						"907400000000021:5)(1:C18:10.99749774696401718:2.804219806241334818:12.6651966746" +
						"7219718:4.088248189550056618:11.90864115979243618:3.3308172159527163)(1:C1:818:2" +
						".000000000000000918:10.08635433413559818:2.277622396529952918:9.0523721335072214" +
						"17:2.000208021193536)(1:C7:10.59541:56:9.10981:28:10.076487:3.20837)(1:F18:10.59" +
						"54000000000021:51:10:)(1:F18:10.5954000000000022:111:11:1)(1:L1:82:11)(1:L1:82:1" +
						"4)(1:C7:10.59542:116:9.10982:148:10.076488:12.79163)(1:F18:10.5954000000000022:1" +
						"11:10:)(1:F1:51:81:11:1)(1:C6:5.404618:10.99999999999999818:4.994361564547472417" +
						":9.01396527660443618:5.130548613744021918:10.023755557349983)(1:L1:818:10.999999" +
						"999999998)(1:L1:81:8)(1:F1:51:81:10:)(1:F1:81:51:11:1)(1:L1:81:8)(1:L2:111:8)(1:" +
						"C18:10.59539999999999818:5.000000000000000918:11.00563843545252518:6.98603472339" +
						"5565718:10.86945138625597618:5.9762444426500148)(1:F1:81:51:10:)(1:F6:5.40461:51" +
						":11:1)(1:L1:81:5)(1:L1:81:2)(1:C6:5.40461:56:6.89021:27:5.923527:3.20837)(1:F6:5" +
						".40461:51:10:)))(4:Path(4:Fill(5:Solid9:#FFEBEBEB))(8:Segments(1:F1:81:21:11:1)(" +
						"1:C18:3.757359312880715218:3.757359312880714318:6.40931135905218511:218:4.882146" +
						"037651328818:2.6325725881101012)(1:C1:218:7.999999999999999118:2.632572588110101" +
						"618:4.88214603765132791:218:6.4093113590521842)(1:C18:3.757359312880715218:12.24" +
						"264068711928618:1.999999999999999817:9.59068864094781418:2.632572588110101218:11" +
						".117853962348672)(1:C18:7.99999999999999912:1418:4.882146037651327916:13.3674274" +
						"11889918:6.40931135905218422:14)(1:C18:12.24264068711928418:12.24264068711928617" +
						":9.5906886409478142:1417:11.1178539623486716:13.3674274118899)(1:C2:1418:8.00000" +
						"0000000001818:13.36742741188989818:11.1178539623486722:1418:9.5906886409478176)(" +
						"1:C18:13.19615242270663218:5.00000000000000092:1418:6.946858429339694218:13.7227" +
						"2320803678618:5.9120473539732714)(1:C2:1117:2.80384757729336818:12.6695816373764" +
						"7816:4.0879526460267318:11.91204735397327118:3.3304183626235218)(1:C18:7.9999999" +
						"9999999731:218:10.08795264602672918:2.277276791963214218:9.053141570660304918:1." +
						"9999999999999996)(1:F1:81:21:10:)(1:F1:84:13.51:11:1)(1:C18:4.110912703473989218" +
						":11.88908729652601118:6.54186874579783684:13.518:5.141967201180384518:12.9201417" +
						"94232407)(1:C3:2.51:818:3.079858205767593818:10.8580327988196153:2.518:9.4581312" +
						"542021632)(1:C18:4.110912703473989218:4.11091270347398833:2.518:6.54186874579783" +
						"5118:3.079858205767592918:5.1419672011803836)(1:C18:7.99999999999999913:2.518:5." +
						"141967201180384518:3.079858205767592918:6.541868745797835918:2.5000000000000004)" +
						"(1:C18:11.88908729652601118:4.110912703473987418:9.458131254202163218:2.49999999" +
						"9999999618:10.85803279881961518:3.0798582057675921)(1:C4:13.518:7.99999999999999" +
						"8218:12.92014179423240718:5.14196720118038284:13.518:6.5418687457978351)(1:C18:1" +
						"2.7631397208144155:10.754:13.516:8.9653797731052818:13.24582960736705518:9.91395" +
						"65921911679)(1:C18:10.75000000000000218:12.76313972081441318:12.2804498342617751" +
						"8:11.58604340780883218:11.58604340780883218:12.280449834261772)(1:C1:818:13.5000" +
						"0000000000216:9.9139565921911718:13.24582960736705518:8.965379773105281618:13.50" +
						"0000000000002)(1:F1:84:13.51:10:))))(8:ClipMask)))");
			}
			
			/// <summary>Loads the image for Themed Icon Shader theme aspect GrayDark.</summary>
			public global::JetBrains.Application.UI.Icons.Images.TiImage Load_GrayDark()
			{
				return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromCanonicalSExpressionAsciiString("(7:TiImage2:v1(6:Vector(4:Size5:16,16)(7:Drawing(4:Path(4:Fill(5:Solid9:#FF252525" +
						"))(8:Segments(1:F2:161:81:11:1)(1:C1:82:162:1618:12.41827799864634918:12.4182779" +
						"986463492:16)(1:C0:1:818:3.58172200135365152:160:18:12.418277998646349)(1:C1:80:" +
						"0:18:3.581722001353651518:3.58172200135365150:)(1:C2:161:818:12.4182779986463490" +
						":2:1618:3.5817220013536515)))(4:Path(4:Fill(5:Solid9:#FFC4C4C4))(8:Segments(1:F2" +
						":151:81:11:1)(1:C1:82:152:1518:11.86599324881555418:11.8659932488155542:15)(1:C1" +
						":11:818:4.13400675118444562:151:118:11.865993248815554)(1:C1:81:11:118:4.1340067" +
						"51184445618:4.13400675118444561:1)(1:C2:151:818:11.8659932488155541:12:1518:4.13" +
						"40067511844456)))(4:Path(4:Fill(5:Solid9:#FF292929))(8:Segments(1:F2:141:81:11:1" +
						")(1:C1:82:142:1418:11.31370849898476118:11.3137084989847612:14)(1:C1:21:818:4.68" +
						"629150101523882:141:218:11.313708498984761)(1:C1:81:21:218:4.686291501015238818:" +
						"4.68629150101523881:2)(1:C2:141:818:11.3137084989847611:22:1418:4.68629150101523" +
						"88)))(4:Path(4:Fill(5:Solid9:#FFC4C4C4))(8:Segments(1:F1:82:141:11:1)(1:C18:5.00" +
						"2507923695814518:13.19577769292814316:6.9476295615990718:13.99979022284731318:5." +
						"913649429685886418:13.722375015071698)(1:C18:2.80927000000000062:1118:4.09136641" +
						"7705742718:12.66918037078458818:3.334812478635425418:11.911750342350555)(1:L6:5." +
						"40462:11)(1:C1:82:147:5.923528:12.791636:6.89022:14)(1:F1:82:141:10:)(1:F2:111:8" +
						"1:11:1)(1:C18:10.5953999999999982:1118:11.00563843545252518:9.013965276604434318" +
						":10.86945138625597618:10.023755557349986)(1:L18:13.1907399999999982:11)(1:C2:141" +
						":818:13.72078583548442118:10.08913926908939718:14.00005651479703418:9.0538576069" +
						"068615)(1:F2:111:81:10:)(1:F6:5.40461:51:11:1)(1:L7:2.809271:5)(1:C1:218:7.99999" +
						"9999999996418:2.279220668244191617:5.91085975459526318:1.999946521398786416:6.94" +
						"614147829219)(1:L1:518:7.9999999999999964)(1:C18:5.404600000000002118:5.00000000" +
						"0000005318:4.994361564547475918:6.986034723395565718:5.130548613744025518:5.9762" +
						"444426500139)(1:F6:5.40461:51:10:)(1:F18:10.5954000000000021:51:11:1)(1:L18:13.1" +
						"907400000000021:5)(1:C18:10.99749774696401718:2.804219806241334818:12.6651966746" +
						"7219718:4.088248189550056618:11.90864115979243618:3.3308172159527163)(1:C1:818:2" +
						".000000000000000918:10.08635433413559818:2.277622396529952918:9.0523721335072214" +
						"17:2.000208021193536)(1:C7:10.59541:56:9.10981:28:10.076487:3.20837)(1:F18:10.59" +
						"54000000000021:51:10:)(1:F18:10.5954000000000022:111:11:1)(1:L1:82:11)(1:L1:82:1" +
						"4)(1:C7:10.59542:116:9.10982:148:10.076488:12.79163)(1:F18:10.5954000000000022:1" +
						"11:10:)(1:F1:51:81:11:1)(1:C6:5.404618:10.99999999999999818:4.994361564547472417" +
						":9.01396527660443618:5.130548613744021918:10.023755557349983)(1:L1:818:10.999999" +
						"999999998)(1:L1:81:8)(1:F1:51:81:10:)(1:F1:81:51:11:1)(1:L1:81:8)(1:L2:111:8)(1:" +
						"C18:10.59539999999999818:5.000000000000000918:11.00563843545252518:6.98603472339" +
						"5565718:10.86945138625597618:5.9762444426500148)(1:F1:81:51:10:)(1:F6:5.40461:51" +
						":11:1)(1:L1:81:5)(1:L1:81:2)(1:C6:5.40461:56:6.89021:27:5.923527:3.20837)(1:F6:5" +
						".40461:51:10:)))(4:Path(4:Fill(5:Solid9:#FF292929))(8:Segments(1:F1:81:21:11:1)(" +
						"1:C18:3.757359312880715218:3.757359312880714318:6.40931135905218511:218:4.882146" +
						"037651328818:2.6325725881101012)(1:C1:218:7.999999999999999118:2.632572588110101" +
						"618:4.88214603765132791:218:6.4093113590521842)(1:C18:3.757359312880715218:12.24" +
						"264068711928618:1.999999999999999817:9.59068864094781418:2.632572588110101218:11" +
						".117853962348672)(1:C18:7.99999999999999912:1418:4.882146037651327916:13.3674274" +
						"11889918:6.40931135905218422:14)(1:C18:12.24264068711928418:12.24264068711928617" +
						":9.5906886409478142:1417:11.1178539623486716:13.3674274118899)(1:C2:1418:8.00000" +
						"0000000001818:13.36742741188989818:11.1178539623486722:1418:9.5906886409478176)(" +
						"1:C18:13.19615242270663218:5.00000000000000092:1418:6.946858429339694218:13.7227" +
						"2320803678618:5.9120473539732714)(1:C2:1117:2.80384757729336818:12.6695816373764" +
						"7816:4.0879526460267318:11.91204735397327118:3.3304183626235218)(1:C18:7.9999999" +
						"9999999731:218:10.08795264602672918:2.277276791963214218:9.053141570660304918:1." +
						"9999999999999996)(1:F1:81:21:10:)(1:F1:84:13.51:11:1)(1:C18:4.110912703473989218" +
						":11.88908729652601118:6.54186874579783684:13.518:5.141967201180384518:12.9201417" +
						"94232407)(1:C3:2.51:818:3.079858205767593818:10.8580327988196153:2.518:9.4581312" +
						"542021632)(1:C18:4.110912703473989218:4.11091270347398833:2.518:6.54186874579783" +
						"5118:3.079858205767592918:5.1419672011803836)(1:C18:7.99999999999999913:2.518:5." +
						"141967201180384518:3.079858205767592918:6.541868745797835918:2.5000000000000004)" +
						"(1:C18:11.88908729652601118:4.110912703473987418:9.458131254202163218:2.49999999" +
						"9999999618:10.85803279881961518:3.0798582057675921)(1:C4:13.518:7.99999999999999" +
						"8218:12.92014179423240718:5.14196720118038284:13.518:6.5418687457978351)(1:C18:1" +
						"2.7631397208144155:10.754:13.516:8.9653797731052818:13.24582960736705518:9.91395" +
						"65921911679)(1:C18:10.75000000000000218:12.76313972081441318:12.2804498342617751" +
						"8:11.58604340780883218:11.58604340780883218:12.280449834261772)(1:C1:818:13.5000" +
						"0000000000216:9.9139565921911718:13.24582960736705518:8.965379773105281618:13.50" +
						"0000000000002)(1:F1:84:13.51:10:))))(8:ClipMask)))");
			}
			
			/// <summary>Returns the set of theme images for Themed Icon Shader.</summary>
			public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] GetThemeImages()
			{
				return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] {
						new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Color", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Color)),
						new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Gray", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Gray)),
						new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("GrayDark", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_GrayDark))};
			}
		}
		#endregion
	}
}
