//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Windows.Markup.XmlnsDefinitionAttribute("urn:shemas-jetbrains-com:ui-application-unity-object-type", "JetBrains.ReSharper.Plugins.Unity.Resources.Icons")]

namespace JetBrains.ReSharper.Plugins.Unity.Resources.Icons
{
    public sealed class UnityObjectTypeThemedIcons
    {
        /// <summary>
        ///	<para>
        ///		<para>UnityComponent Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="UnityComponent"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///
        ///                   pppppppppppp
        ///                   RR''''''''RR
        ///     EEEEEEEEEEEE  ##::::::::##
        ///     aa        aa  00^^^^^^^^00
        ///     PP        PP  MM;;;;;;;;MM
        ///     VV````````VV  NNNNNNNNNNNN
        ///     kk````````kk
        ///     4444444444444444444444
        ///     AA````````AA        AA
        ///     XX........XX````````XX
        ///     RR________RR--------RR
        ///     ##::::::::##''''''''##
        ///     8888888888888888888888
        ///
        ///
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:RirezypThemedIconsThemedIcons+UnityComponent}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(RirezypThemedIconsThemedIcons.UnityComponent))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = RirezypThemedIconsThemedIcons.UnityComponent.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;RirezypThemedIconsThemedIcons.UnityComponent&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class UnityComponent : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="UnityComponent">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id =
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(UnityComponent));

            /// <summary>Loads the image for Themed Icon UnityComponent theme aspect Color.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Color()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M0,0L16,0L16,1" +
                    "6L0,16Z\' fill=\'#FFFFFF\' opacity=\'0\'/><linearGradient id=\'F1\' x1=\'0.5\' y1=\'0\' x2=" +
                    "\'0.5\' y2=\'1\'><stop offset=\'0\' stop-color=\'#5D6C75\'/><stop offset=\'1\' stop-color=" +
                    "\'#304145\'/></linearGradient><path d=\'M8,8L8,3L2,3L2,8L2,9L2,14L7,14L8,14L13,14L1" +
                    "3,8L8,8Z\' fill=\'url(#F1)\'/><linearGradient id=\'F2\' x1=\'0.5\' y1=\'0.00625000000000" +
                    "00888\' x2=\'0.5\' y2=\'1\'><stop offset=\'0\' stop-color=\'#F4FFE7\'/><stop offset=\'1\' s" +
                    "top-color=\'#D3D02A\'/></linearGradient><path d=\'M8,9L12,9L12,13L8,13Z\' fill=\'url(" +
                    "#F2)\'/><linearGradient id=\'F3\' x1=\'0.5\' y1=\'0.016500000000000181\' x2=\'0.5\' y2=\'1" +
                    ".0505\'><stop offset=\'0\' stop-color=\'#FFE0D0\'/><stop offset=\'1\' stop-color=\'#FFA6" +
                    "57\'/></linearGradient><path d=\'M3,9L7,9L7,13L3,13Z\' fill=\'url(#F3)\'/><linearGrad" +
                    "ient id=\'F4\' x1=\'0.5\' y1=\'0.016499999999999959\' x2=\'0.5\' y2=\'1.0505\'><stop offse" +
                    "t=\'0\' stop-color=\'#D0FFE8\'/><stop offset=\'1\' stop-color=\'#45FFA5\'/></linearGradi" +
                    "ent><path d=\'M3,4L7,4L7,8L3,8Z\' fill=\'url(#F4)\'/><linearGradient id=\'F5\' x1=\'0.5" +
                    "\' y1=\'0.00633333333333333\' x2=\'0.5\' y2=\'0.99449999999999983\'><stop offset=\'0\' st" +
                    "op-color=\'#00539C\'/><stop offset=\'1\' stop-color=\'#002D54\'/></linearGradient><pat" +
                    "h d=\'M9,1L15,1L15,7L9,7Z\' fill=\'url(#F5)\'/><linearGradient id=\'F6\' x1=\'0.5\' y1=\'" +
                    "0\' x2=\'0.5\' y2=\'1\'><stop offset=\'0\' stop-color=\'#81E3FF\'/><stop offset=\'1\' stop-" +
                    "color=\'#00AAFF\'/></linearGradient><path d=\'M10,2L14,2L14,6L10,6Z\' fill=\'url(#F6)" +
                    "\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon UnityComponent theme aspect Gray.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Gray()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M9,1L15,1L15,7L9,7Z' fill='#F4F4F4'/><path d='M10,2L14,2L14,6L10,6Z' fill='#00539C'/><path d='M9,7L9,3L2,3L2,14L13,14L13,7L9,7Z' fill='#F4F4F4'/><path d='M3,8L8,8L8,13L3,13Z' fill='#323232'/><path d='M3,4L8,4L8,9L3,9Z' fill='#323232'/><path d='M7,8L12,8L12,13L7,13Z' fill='#323232'/><path d='M8,9L11,9L11,12L8,12Z' fill='#EBEBEB'/><path d='M4,9L7,9L7,12L4,12Z' fill='#EBEBEB'/><path d='M4,5L7,5L7,8L4,8Z' fill='#EBEBEB'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon UnityComponent theme aspect GrayDark.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_GrayDark()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M9,1L15,1L15,7L9,7Z' fill='#252525'/><path d='M10,2L14,2L14,6L10,6Z' fill='#7CBEFF'/><path d='M9,7L9,3L2,3L2,14L13,14L13,7L9,7Z' fill='#252525'/><path d='M3,8L8,8L8,13L3,13Z' fill='#C4C4C4'/><path d='M3,4L8,4L8,9L3,9Z' fill='#C4C4C4'/><path d='M7,8L12,8L12,13L7,13Z' fill='#C4C4C4'/><path d='M8,9L11,9L11,12L8,12Z' fill='#292929'/><path d='M4,9L7,9L7,12L4,12Z' fill='#292929'/><path d='M4,5L7,5L7,8L4,8Z' fill='#292929'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon UnityComponent.</summary>
            public override
                global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                GetThemeImages()
            {
                return new
                    global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                    {
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage("Color",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(this.Load_Color)),
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage("Gray",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(this.Load_Gray)),
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage("GrayDark",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(this.Load_GrayDark))
                    };
            }
        }

        /// <summary>
        ///	<para>
        ///		<para>UnityGameObject Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="UnityGameObject"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///               @@@@@@
        ///               @@  @@
        ///               @@  @@
        ///               @@  @@
        ///             _L$BPP0%c_
        ///           +KpE|TrrT)5wGc
        ///         `5#2;'``'^+!;=iDP-
        ///         ?8u*`     ;==^~T8t
        ///         40T*^-  `_=^~",,0#
        ///         sMZ++!;==^~",__*Me
        ///        ^RQM{;==^~",___*8N#;
        ///     'Zg@4=l%DY+^,_"^7G$j=P@gS_
        ///   ?W@BL`'lg@8Aw8QQ0HA8@gY_`*8@NJ
        ///   @@j`*8@NJ`           ?W@M?`l@@
        ///    j@@gS_                'Zg@@h`
        ///
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:RirezypThemedIconsThemedIcons+UnityGameObject}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(RirezypThemedIconsThemedIcons.UnityGameObject))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = RirezypThemedIconsThemedIcons.UnityGameObject.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;RirezypThemedIconsThemedIcons.UnityGameObject&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class UnityGameObject : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="UnityGameObject">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id =
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(UnityGameObject));

            /// <summary>Loads the image for Themed Icon UnityGameObject theme aspect Color.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Color()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M0,0L16,0L16,1" +
                    "6L0,16Z\' fill=\'#FFFFFF\' opacity=\'0\'/><path d=\'M1,12.749L1,13.629L2.217,15L3,15L8" +
                    ".5,10.875L14,15L14.781,15L16,13.63L16,12.75L10,8.25L10,0L7,0L7,8.25L1,12.749Z\' f" +
                    "ill=\'#000000\'/><path d=\'M9,8.75L9,1L8,1L8,8.75L2,13.249L2.666,14L8.5,9.625L14.33" +
                    "2,14L15,13.25L9,8.75Z\' fill=\'#FFFEBD\'/><linearGradient id=\'F3\' x1=\'0.5\' y1=\'0.00" +
                    "63333333333333575\' x2=\'0.5\' y2=\'0.99444444444444424\'><stop offset=\'0\' stop-color" +
                    "=\'#00539C\'/><stop offset=\'1\' stop-color=\'#002D54\'/></linearGradient><path d=\'M13" +
                    ",8.5C13,10.985281374238571,10.985281374238571,13,8.5,13C6.0147186257614287,13,4," +
                    "10.985281374238571,4,8.5C4,6.0147186257614287,6.0147186257614287,4,8.5,4C10.9852" +
                    "81374238571,4,13,6.0147186257614287,13,8.5Z\' fill=\'url(#F3)\'/><linearGradient id" +
                    "=\'F4\' x1=\'0.35242857142857142\' y1=\'0.35242857142857142\' x2=\'0.86214285714285721\'" +
                    " y2=\'0.86214285714285721\'><stop offset=\'0\' stop-color=\'#40A6FF\'/><stop offset=\'1" +
                    "\' stop-color=\'#B5DEFF\'/></linearGradient><path d=\'M12,8.5C12,10.432996624407778," +
                    "10.432996624407778,12,8.5,12C6.5670033755922228,12,5,10.432996624407778,5,8.5C5," +
                    "6.5670033755922228,6.5670033755922228,5,8.5,5C10.432996624407778,5,12,6.56700337" +
                    "55922228,12,8.5Z\' fill=\'url(#F4)\'/><path d=\'M9,7.5C9,8.32842712474619,8.32842712" +
                    "474619,9,7.5,9C6.67157287525381,9,6,8.32842712474619,6,7.5C6,6.67157287525381,6." +
                    "67157287525381,6,7.5,6C8.32842712474619,6,9,6.67157287525381,9,7.5Z\' fill=\'#FFFF" +
                    "FF\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon UnityGameObject theme aspect Gray.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Gray()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M1,12.749L1,13.629L2.217,15L3,15L8.5,10.875L14,15L14.781,15L16,13.63L16,12.75L10,8.25L10,0L7,0L7,8.25L1,12.749Z' fill='#F4F4F4'/><path d='M9,8.75L9,1L8,1L8,8.75L2,13.249L2.666,14L8.5,9.625L14.332,14L15,13.25L9,8.75Z' fill='#323232'/><path d='M13,8.5C13,10.985281374238571,10.985281374238571,13,8.5,13C6.0147186257614287,13,4,10.985281374238571,4,8.5C4,6.0147186257614287,6.0147186257614287,4,8.5,4C10.985281374238571,4,13,6.0147186257614287,13,8.5Z' fill='#F4F4F4'/><path d='M12,8.5C12,10.432996624407778,10.432996624407778,12,8.5,12C6.5670033755922228,12,5,10.432996624407778,5,8.5C5,6.5670033755922228,6.5670033755922228,5,8.5,5C10.432996624407778,5,12,6.5670033755922228,12,8.5Z' fill='#1BA1E2'/><path d='M9,7.5C9,8.32842712474619,8.32842712474619,9,7.5,9C6.67157287525381,9,6,8.32842712474619,6,7.5C6,6.67157287525381,6.67157287525381,6,7.5,6C8.32842712474619,6,9,6.67157287525381,9,7.5Z' fill='#FFFFFF'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon UnityGameObject theme aspect GrayDark.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_GrayDark()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromTiSvg(
                    @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M1,12.749L1,13.629L2.217,15L3,15L8.5,10.875L14,15L14.781,15L16,13.63L16,12.75L10,8.25L10,0L7,0L7,8.25L1,12.749Z' fill='#252525'/><path d='M9,8.75L9,1L8,1L8,8.75L2,13.249L2.666,14L8.5,9.625L14.332,14L15,13.25L9,8.75Z' fill='#C4C4C4'/><path d='M13,8.5C13,10.985281374238571,10.985281374238571,13,8.5,13C6.0147186257614287,13,4,10.985281374238571,4,8.5C4,6.0147186257614287,6.0147186257614287,4,8.5,4C10.985281374238571,4,13,6.0147186257614287,13,8.5Z' fill='#252525'/><path d='M12,8.5C12,10.432996624407778,10.432996624407778,12,8.5,12C6.5670033755922228,12,5,10.432996624407778,5,8.5C5,6.5670033755922228,6.5670033755922228,5,8.5,5C10.432996624407778,5,12,6.5670033755922228,12,8.5Z' fill='#2BAAE8'/><path d='M9,7.5C9,8.32842712474619,8.32842712474619,9,7.5,9C6.67157287525381,9,6,8.32842712474619,6,7.5C6,6.67157287525381,6.67157287525381,6,7.5,6C8.32842712474619,6,9,6.67157287525381,9,7.5Z' fill='#FFFFFF'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon UnityGameObject.</summary>
            public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                ThemedIconThemeImage[]
                GetThemeImages()
            {
                return new
                    global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                    {
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage(
                                "Color",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(
                                        this.Load_Color)),
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage(
                                "Gray",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(
                                        this.Load_Gray)),
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                            ThemedIconThemeImage(
                                "GrayDark",
                                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.
                                    LoadImageDelegate(
                                        this.Load_GrayDark))
                    };
            }
        }
    }
}
