//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrains.ReSharper.Plugins.Unity.Resources.Icons
{
    public sealed class InsightUnityIcons
    {
                            [JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute]
    public sealed class InsightOdin : JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
    {
      public static JetBrains.UI.Icons.IconId Id = new JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightOdin));
      private const string Image_Color = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M9.63,1.5L15.22,11.18L7.1,11.18L8.12,9.42L12.169999999999998,9.42L8.62,3.27L9.6399999999999988,1.51ZM9.63,1.5M2.8200000000000012,11.18L6.370000000000001,5.0299999999999994L8.39,8.53L10.43,8.53L6.37,1.5L0.78,11.18L2.8200000000000003,11.18ZM12.57,12.24L5.4700000000000006,12.24L7.49,8.74L6.4700000000000006,6.98L2.410000000000001,14.010000000000002L13.580000000000002,14.010000000000002L12.560000000000002,12.250000000000002ZM12.57,12.24' fill='#9AA7B0' opacity='0.8'/></g></svg>";
      private const string Image_Gray = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M9.63,1.5L15.22,11.18L7.1,11.18L8.12,9.42L12.169999999999998,9.42L8.62,3.27L9.6399999999999988,1.51ZM9.63,1.5M2.8200000000000012,11.18L6.370000000000001,5.0299999999999994L8.39,8.53L10.43,8.53L6.37,1.5L0.78,11.18L2.8200000000000003,11.18ZM12.57,12.24L5.4700000000000006,12.24L7.49,8.74L6.4700000000000006,6.98L2.410000000000001,14.010000000000002L13.580000000000002,14.010000000000002L12.560000000000002,12.250000000000002ZM12.57,12.24' fill='#9AA7B0' opacity='0.8'/></g></svg>";
      private const string Image_GrayDark = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M9.63,1.5L15.22,11.18L7.1,11.18L8.12,9.42L12.169999999999998,9.42L8.62,3.27L9.6399999999999988,1.51ZM9.63,1.5M2.8200000000000012,11.18L6.370000000000001,5.0299999999999994L8.39,8.53L10.43,8.53L6.37,1.5L0.78,11.18L2.8200000000000003,11.18ZM12.57,12.24L5.4700000000000006,12.24L7.49,8.74L6.4700000000000006,6.98L2.410000000000001,14.010000000000002L13.580000000000002,14.010000000000002L12.560000000000002,12.250000000000002ZM12.57,12.24' fill='#9AA7B0' opacity='0.8'/></g></svg>";
      private const string Image_RiderDark = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M9.63,1.5L15.22,11.18L7.1,11.18L8.12,9.42L12.169999999999998,9.42L8.62,3.27L9.6399999999999988,1.51ZM9.63,1.5M2.8200000000000012,11.18L6.370000000000001,5.0299999999999994L8.39,8.53L10.43,8.53L6.37,1.5L0.78,11.18L2.8200000000000003,11.18ZM12.57,12.24L5.4700000000000006,12.24L7.49,8.74L6.4700000000000006,6.98L2.410000000000001,14.010000000000002L13.580000000000002,14.010000000000002L12.560000000000002,12.250000000000002ZM12.57,12.24' fill='#9AA7B0' opacity='0.8'/></g></svg>";
      private const string Image_RiderDay = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M4.27,9.07L3.2,9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.02,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.1860759521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.1525139403759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4.28,9.07ZM4.27,9.07' fill='#9AA7B0'/><path d='M12.02,11.57L10.29,11.57L10.829999999999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12.87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L12.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02,11.57' fill='#9AA7B0'/><path d='M14.75,9.45L10.629999999999999,2.3099999999999996C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.3099999999999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,10.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.75,9.45' fill='#9AA7B0'/></g></svg>";
      private const string Image_RiderLight = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M9.63,1.5L15.22,11.18L7.1,11.18L8.12,9.42L12.169999999999998,9.42L8.62,3.27L9.6399999999999988,1.51ZM9.63,1.5M2.8200000000000012,11.18L6.370000000000001,5.0299999999999994L8.39,8.53L10.43,8.53L6.37,1.5L0.78,11.18L2.8200000000000003,11.18ZM12.57,12.24L5.4700000000000006,12.24L7.49,8.74L6.4700000000000006,6.98L2.410000000000001,14.010000000000002L13.580000000000002,14.010000000000002L12.560000000000002,12.250000000000002ZM12.57,12.24' fill='#9AA7B0' opacity='0.8'/></g></svg>";
      private const string Image_RiderNight = "<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M4.27,9.07L3.2,9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.02,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.1860759521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.1525139403759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4.28,9.07ZM4.27,9.07' fill='#9AA7B0'/><path d='M12.02,11.57L10.29,11.57L10.829999999999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12.87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L12.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02,11.57' fill='#9AA7B0'/><path d='M14.75,9.45L10.629999999999999,2.3099999999999996C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.3099999999999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,10.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.75,9.45' fill='#9AA7B0'/></g></svg>";
    }
        #region InsightHot
        /// <summary>
        ///	<para>
        ///		<para>InsightHot Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="InsightHot"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:BumigydThemedIconsThemedIcons+InsightHot}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(BumigydThemedIconsThemedIcons.InsightHot))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = BumigydThemedIconsThemedIcons.InsightHot.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;BumigydThemedIconsThemedIcons.InsightHot&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class InsightHot : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="InsightHot">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id = new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightHot));

            /// <summary>Loads the image for Themed Icon InsightHot theme aspect Default.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_Default()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(@"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path fill-rule='evenodd' d='M9.6387,11.2656C9.2747,12.1556,8.2987,13.0716,7.2817,13.0716C6.5867,13.0716,5.4207,12.7716,5.4207,10.7626C5.4207,8.9766,6.8137,7.0926,7.5097,6.0236C7.7767,6.9326,7.8567,8.7776,7.3487,10.1946C8.2107,9.8836,9.5767,9.0286,10.0757,7.8686C10.1527,8.6016,10.0827,10.1796,9.6387,11.2656ZM11.0437,3.6256C10.8877,4.6966,10.9667,6.0416,8.8007,7.0786C9.4837,4.3896,8.6857,1.7646,7.2027,0.9996C7.7447,4.7166,3.9997,6.4586,3.9997,10.0436C3.9997,12.9826,5.5857,13.9996,7.1087,13.9996C11.7897,13.9996,11.9997,8.8806,11.9997,7.3636C11.9997,5.8576,11.6917,4.4496,11.0437,3.6256Z' fill='#9AA7B0'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon InsightHot.</summary>
            public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] GetThemeImages()
            {
                return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] {
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Default", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Default))};
            }
        }
        #endregion


		#region InsightUnity
		/// <summary>
		///	<para>
		///		<para>InsightUnity Themed Icon generated identifiers:</para>
		///		<para>— <see cref="InsightUnity"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
		///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
		///		<para>
		///			<code>
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///                                 
		///</code>
		///		</para>
		///	</para>
		///</summary>
		///<remarks>
		///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
		///</remarks>
		///<example>
		///	<code>&lt;Image Source="{icons:ThemedIcon myres:FefaxulThemedIconsThemedIcons+InsightUnity}" /&gt;        &lt;!-- XAML --&gt;</code>
		///</example>
		///<example>
		///	<code>[Item(Name="Sample", Icon=typeof(FefaxulThemedIconsThemedIcons.InsightUnity))]        // C# Type attribute</code>
		///</example>
		///<example>
		///	<code>IconId iconid = FefaxulThemedIconsThemedIcons.InsightUnity.Id;        // IconId identifier object</code>
		///</example>
		///<example>
		///	<code>themediconmanager.GetIcon&lt;FefaxulThemedIconsThemedIcons.InsightUnity&gt;()        // Icon image for rendering</code>
		///</example>
		[global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
		public sealed class InsightUnity : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
		{
			
			/// <inheritdoc cref="InsightUnity">identifier class</inheritdoc>
			public static global::JetBrains.UI.Icons.IconId Id = new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightUnity));
			
			/// <summary>Loads the image for Themed Icon InsightUnity theme aspect Default.</summary>
			public global::JetBrains.Util.Icons.TiImage Load_Default()
			{
				return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(@"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M13,9.452L13,4.732L9,2.423L9,4.732L10.214,5.433L8,6.738L5.786,5.433L7,4.732L7,2.423L3,4.732L3,9.453L5,8.274L5,6.828L7.2,8.124L7.2,10.717L5.984,10.015L4.005,11.182L8,13.488L11.995,11.181L10.016,10.015L8.8,10.717L8.8,8.124L11,6.828L11,8.274L13,9.452ZM13,9.452' fill='#9AA7B0'/></g></svg>");
			}
			
			/// <summary>Returns the set of theme images for Themed Icon InsightUnity.</summary>
			public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] GetThemeImages()
			{
				return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] {
						new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Default", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Default))};
			}
		}
		#endregion
        
        #region InsightOdin

        /// <summary>
        ///	<para>
        ///		<para>InsightOdin Themed Icon generated identifiers:</para>
        ///		<para>— <see cref="InsightOdin"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
        ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
        ///		<para>
        ///			<code>
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///                                 
        ///</code>
        ///		</para>
        ///	</para>
        ///</summary>
        ///<remarks>
        ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
        ///</remarks>
        ///<example>
        ///	<code>&lt;Image Source="{icons:ThemedIcon myres:SalyvuvThemedIconsThemedIcons+InsightOdin}" /&gt;        &lt;!-- XAML --&gt;</code>
        ///</example>
        ///<example>
        ///	<code>[Item(Name="Sample", Icon=typeof(SalyvuvThemedIconsThemedIcons.InsightOdin))]        // C# Type attribute</code>
        ///</example>
        ///<example>
        ///	<code>IconId iconid = SalyvuvThemedIconsThemedIcons.InsightOdin.Id;        // IconId identifier object</code>
        ///</example>
        ///<example>
        ///	<code>themediconmanager.GetIcon&lt;SalyvuvThemedIconsThemedIcons.InsightOdin&gt;()        // Icon image for rendering</code>
        ///</example>
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        public sealed class InsightOdin : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="InsightOdin">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id =
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(InsightOdin));

            /// <summary>Loads the image for Themed Icon InsightOdin theme aspect Color.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_Color()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M4.27,9.07L3.2" +
                    ",9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.0" +
                    "2,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.18607" +
                    "59521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.152513940" +
                    "3759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360" +
                    "497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4." +
                    "28,9.07ZM4.27,9.07\' fill=\'#9AA7B0\'/><path d=\'M12.02,11.57L10.29,11.57L10.8299999" +
                    "99999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12." +
                    "87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999" +
                    "995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L1" +
                    "2.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C" +
                    "12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02," +
                    "11.57\' fill=\'#9AA7B0\'/><path d=\'M14.75,9.45L10.629999999999999,2.309999999999999" +
                    "6C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.309999999" +
                    "9999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999" +
                    "994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,1" +
                    "0.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C" +
                    "14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.7" +
                    "5,9.45\' fill=\'#9AA7B0\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon InsightOdin theme aspect Gray.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_Gray()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M4.27,9.07L3.2" +
                    ",9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.0" +
                    "2,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.18607" +
                    "59521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.152513940" +
                    "3759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360" +
                    "497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4." +
                    "28,9.07ZM4.27,9.07\' fill=\'#9AA7B0\'/><path d=\'M12.02,11.57L10.29,11.57L10.8299999" +
                    "99999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12." +
                    "87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999" +
                    "995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L1" +
                    "2.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C" +
                    "12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02," +
                    "11.57\' fill=\'#9AA7B0\'/><path d=\'M14.75,9.45L10.629999999999999,2.309999999999999" +
                    "6C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.309999999" +
                    "9999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999" +
                    "994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,1" +
                    "0.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C" +
                    "14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.7" +
                    "5,9.45\' fill=\'#9AA7B0\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon InsightOdin theme aspect GrayDark.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_GrayDark()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M4.27,9.07L3.2" +
                    ",9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.0" +
                    "2,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.18607" +
                    "59521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.152513940" +
                    "3759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360" +
                    "497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4." +
                    "28,9.07ZM4.27,9.07\' fill=\'#9AA7B0\'/><path d=\'M12.02,11.57L10.29,11.57L10.8299999" +
                    "99999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12." +
                    "87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999" +
                    "995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L1" +
                    "2.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C" +
                    "12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02," +
                    "11.57\' fill=\'#9AA7B0\'/><path d=\'M14.75,9.45L10.629999999999999,2.309999999999999" +
                    "6C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.309999999" +
                    "9999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999" +
                    "994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,1" +
                    "0.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C" +
                    "14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.7" +
                    "5,9.45\' fill=\'#9AA7B0\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon InsightOdin theme aspect RiderDark.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_RiderDark()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M4.27,9.07L3.2" +
                    ",9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.0" +
                    "2,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.18607" +
                    "59521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.152513940" +
                    "3759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360" +
                    "497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4." +
                    "28,9.07ZM4.27,9.07\' fill=\'#9AA7B0\'/><path d=\'M12.02,11.57L10.29,11.57L10.8299999" +
                    "99999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12." +
                    "87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999" +
                    "995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L1" +
                    "2.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C" +
                    "12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02," +
                    "11.57\' fill=\'#9AA7B0\'/><path d=\'M14.75,9.45L10.629999999999999,2.309999999999999" +
                    "6C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.309999999" +
                    "9999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999" +
                    "994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,1" +
                    "0.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C" +
                    "14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.7" +
                    "5,9.45\' fill=\'#9AA7B0\'/></g></svg>");
            }

            /// <summary>Loads the image for Themed Icon InsightOdin theme aspect RiderLight.</summary>
            public global::JetBrains.Util.Icons.TiImage Load_RiderLight()
            {
                return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
                    "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
                    "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M4.27,9.07L3.2" +
                    ",9.07L6.02,4.1800000000000006L8.27,8.07L10,8.07L6.67,2.3C6.54,2.07,6.29,1.92,6.0" +
                    "2,1.92C5.7499999999999991,1.92,5.5,2.06,5.3699999999999992,2.3L1.25,9.44C1.18607" +
                    "59521198276,9.5546395021991355,1.1525139403759597,9.6837426216860454,1.152513940" +
                    "3759597,9.815C1.1525139403759597,9.9462573783139536,1.1860759521198276,10.075360" +
                    "497800864,1.2499999999999998,10.19C1.38,10.42,1.63,10.57,1.9,10.57L3.41,10.57L4." +
                    "28,9.07ZM4.27,9.07\' fill=\'#9AA7B0\'/><path d=\'M12.02,11.57L10.29,11.57L10.8299999" +
                    "99999998,12.5L5.18,12.5L7.43,8.61L6.56,7.1099999999999994L3.2299999999999995,12." +
                    "87C3.0999999999999996,13.1,3.0999999999999996,13.389999999999999,3.2299999999999" +
                    "995,13.62C3.3599999999999994,13.85,3.6099999999999994,14,3.8799999999999994,14L1" +
                    "2.129999999999999,14C12.399999999999999,14,12.649999999999999,13.86,12.78,13.62C" +
                    "12.91,13.379999999999999,12.91,13.1,12.78,12.87L12.03,11.569999999999999ZM12.02," +
                    "11.57\' fill=\'#9AA7B0\'/><path d=\'M14.75,9.45L10.629999999999999,2.309999999999999" +
                    "6C10.36,1.8499999999999996,9.6,1.8499999999999996,9.3299999999999983,2.309999999" +
                    "9999996L8.5799999999999983,3.6099999999999994L9.4499999999999975,5.1099999999999" +
                    "994L9.9899999999999984,4.18L12.809999999999999,9.07L8.32,9.07L7.45,10.57L14.11,1" +
                    "0.57C14.379999999999999,10.57,14.629999999999999,10.43,14.76,10.200000000000001C" +
                    "14.89,9.9700000000000024,14.89,9.6800000000000015,14.76,9.4500000000000011ZM14.7" +
                    "5,9.45\' fill=\'#9AA7B0\'/></g></svg>");
            }

            /// <summary>Returns the set of theme images for Themed Icon InsightOdin.</summary>
            public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                GetThemeImages()
            {
                return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
                {
                    new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
                        "Color",
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
                            this.Load_Color)),
                    new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
                        "Gray",
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
                            this.Load_Gray)),
                    new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
                        "GrayDark",
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
                            this.Load_GrayDark)),
                    new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
                        "RiderDark",
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
                            this.Load_RiderDark)),
                    new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
                        "RiderLight",
                        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
                            this.Load_RiderLight))
                };
            }
        }

        #endregion

    }
}
