// <auto-generated/>

#if INDEPENDENT_BUILD
global using TestAttribute = NUnit.Framework.TestAttribute;
global using TestCaseAttribute = NUnit.Framework.TestCaseAttribute;
global using TestCaseSourceAttribute = NUnit.Framework.TestCaseSourceAttribute;
global using TestFixtureAttribute = NUnit.Framework.TestFixtureAttribute;
global using TestFixtureSourceAttribute = NUnit.Framework.TestFixtureSourceAttribute;
global using SetUpFixtureAttribute = NUnit.Framework.SetUpFixtureAttribute;
global using ExplicitAttribute = NUnit.Framework.ExplicitAttribute;
global using CategoryAttribute = NUnit.Framework.CategoryAttribute;
global using IgnoreAttribute = NUnit.Framework.IgnoreAttribute;
#else
global using TestAttribute = JetBrains.TestFramework.TestAttribute;
global using TestCaseAttribute = JetBrains.TestFramework.TestCaseAttribute;
global using TestCaseSourceAttribute = JetBrains.TestFramework.TestCaseSourceAttribute;
global using TestFixtureAttribute = JetBrains.TestFramework.TestFixtureAttribute;
global using TestFixtureSourceAttribute = JetBrains.TestFramework.TestFixtureSourceAttribute;
global using SetUpFixtureAttribute = JetBrains.TestFramework.SetUpFixtureAttribute;
global using ExplicitAttribute = JetBrains.TestFramework.ExplicitAttribute;
global using CategoryAttribute = JetBrains.TestFramework.CategoryAttribute;
global using IgnoreAttribute = JetBrains.TestFramework.IgnoreAttribute;
#endif