//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if NUNIT_ATTRIBUTE_WRAPPERS
global using TestAttribute = JetBrains.TestFramework.TestAttribute;
global using TestCaseAttribute = JetBrains.TestFramework.TestCaseAttribute;
global using TestCaseSourceAttribute = JetBrains.TestFramework.TestCaseSourceAttribute;
global using TestFixtureAttribute = JetBrains.TestFramework.TestFixtureAttribute;
global using TestFixtureSourceAttribute = JetBrains.TestFramework.TestFixtureSourceAttribute;
global using SetUpFixtureAttribute = JetBrains.TestFramework.SetUpFixtureAttribute;
global using ExplicitAttribute = JetBrains.TestFramework.ExplicitAttribute;
global using CategoryAttribute = JetBrains.TestFramework.CategoryAttribute;
global using IgnoreAttribute = JetBrains.TestFramework.IgnoreAttribute;
#else
global using TestAttribute = NUnit.Framework.TestAttribute;
global using TestCaseAttribute = NUnit.Framework.TestCaseAttribute;
global using TestCaseSourceAttribute = NUnit.Framework.TestCaseSourceAttribute;
global using TestFixtureAttribute = NUnit.Framework.TestFixtureAttribute;
global using TestFixtureSourceAttribute = NUnit.Framework.TestFixtureSourceAttribute;
global using SetUpFixtureAttribute = NUnit.Framework.SetUpFixtureAttribute;
global using ExplicitAttribute = NUnit.Framework.ExplicitAttribute;
global using CategoryAttribute = NUnit.Framework.CategoryAttribute;
global using IgnoreAttribute = NUnit.Framework.IgnoreAttribute;
#endif
[assembly: System.Reflection.AssemblyMetadataAttribute("Root", "Plugins/ReSharperUnity/resharper/resharper-json/test/src/Json.Tests")]

