//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiParser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ApiParser.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AssetPostprocessor_OnGeneratedCSProjectFiles_Description {
            get {
                return ResourceManager.GetString("AssetPostprocessor_OnGeneratedCSProjectFiles_Description", resourceCulture);
            }
        }
        
        internal static string AssetPostprocessor_OnPreGeneratingCSProjectFiles_Description {
            get {
                return ResourceManager.GetString("AssetPostprocessor_OnPreGeneratingCSProjectFiles_Description", resourceCulture);
            }
        }
        
        internal static string AssetPostprocessor_OnGeneratedCSProject_Description {
            get {
                return ResourceManager.GetString("AssetPostprocessor_OnGeneratedCSProject_Description", resourceCulture);
            }
        }
        
        internal static string AssetPostprocessor_OnGeneratedSlnSolution_Description {
            get {
                return ResourceManager.GetString("AssetPostprocessor_OnGeneratedSlnSolution_Description", resourceCulture);
            }
        }
        
        internal static string AssetPostprocessor_OnPostprocessAllAssets_Description {
            get {
                return ResourceManager.GetString("AssetPostprocessor_OnPostprocessAllAssets_Description", resourceCulture);
            }
        }
        
        internal static string MonoBehaviour_OnRectTransformDimensionsChange_Description {
            get {
                return ResourceManager.GetString("MonoBehaviour_OnRectTransformDimensionsChange_Description", resourceCulture);
            }
        }
        
        internal static string ScriptableObject_OnValidate_Description {
            get {
                return ResourceManager.GetString("ScriptableObject_OnValidate_Description", resourceCulture);
            }
        }
        
        internal static string Editor_OnPreSceneGUI_Description {
            get {
                return ResourceManager.GetString("Editor_OnPreSceneGUI_Description", resourceCulture);
            }
        }
        
        internal static string Editor_OnSceneDrag_Description {
            get {
                return ResourceManager.GetString("Editor_OnSceneDrag_Description", resourceCulture);
            }
        }
        
        internal static string Editor_OnSceneDrag_sceneView_Description {
            get {
                return ResourceManager.GetString("Editor_OnSceneDrag_sceneView_Description", resourceCulture);
            }
        }
        
        internal static string Editor_OnSceneDrag_index_Description {
            get {
                return ResourceManager.GetString("Editor_OnSceneDrag_index_Description", resourceCulture);
            }
        }
        
        internal static string Editor_HasFrameBounds_Description {
            get {
                return ResourceManager.GetString("Editor_HasFrameBounds_Description", resourceCulture);
            }
        }
        
        internal static string Editor_OnGetFrameBounds_Description {
            get {
                return ResourceManager.GetString("Editor_OnGetFrameBounds_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_ModifierKeysChanged_Description {
            get {
                return ResourceManager.GetString("EditorWindow_ModifierKeysChanged_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_ShowButton_Description {
            get {
                return ResourceManager.GetString("EditorWindow_ShowButton_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnBecameVisible_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnBecameVisible_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnBecameInvisible_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnBecameInvisible_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnDidOpenScene_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnDidOpenScene_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnAddedAsTab_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnAddedAsTab_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnBeforeRemovedAsTab_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnBeforeRemovedAsTab_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnTabDetached_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnTabDetached_Description", resourceCulture);
            }
        }
        
        internal static string EditorWindow_OnMainWindowMove_Description {
            get {
                return ResourceManager.GetString("EditorWindow_OnMainWindowMove_Description", resourceCulture);
            }
        }
    }
}
