//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrains.ReSharper.Plugins.Yaml.Resources.Icons
{
  public sealed class YamlFileTypeThemedIcons
  {
    #region Yaml
    /// <summary>
    ///	<para>
    ///		<para>Yaml Themed Icon generated identifiers:</para>
    ///		<para>— <see cref="FileYaml"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
    ///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
    ///		<para>
    ///			<code>
    ///
    ///     IIIIIIIIIIIIIIIIII
    ///     YY''''''''''''''YY
    ///     nn==============nn
    ///     eeeeeeeeeeeeeeeeeeeeeeee
    ///           yy''''''''''''''yy
    ///           aa==============aa
    /// wwwwwP.`ywwwwwPPPPPPPPPPPPPPPPPP
    /// 5OT"+AKaHL"TO5  99            99
    ///  jD|~\RDT~|Dj   44____________44
    ///   y8v^Tv^v8y    GGGGGGGGGGGGGGGG
    ///    PBl==lBP     bb            bb
    ///     Mw==wM      qq____________qq
    ///     NX;;XN      RRRRRRRRRRRRRRRR
    ///     gggggg
    ///
    ///</code>
    ///		</para>
    ///	</para>
    ///</summary>
    ///<remarks>
    ///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
    ///</remarks>
    ///<example>
    ///	<code>&lt;Image Source="{icons:ThemedIcon myres:DyzumysThemedIconsThemedIcons+Yaml}" /&gt;        &lt;!-- XAML --&gt;</code>
    ///</example>
    ///<example>
    ///	<code>[Item(Name="Sample", Icon=typeof(DyzumysThemedIconsThemedIcons.Yaml))]        // C# Type attribute</code>
    ///</example>
    ///<example>
    ///	<code>IconId iconid = DyzumysThemedIconsThemedIcons.Yaml.Id;        // IconId identifier object</code>
    ///</example>
    ///<example>
    ///	<code>themediconmanager.GetIcon&lt;DyzumysThemedIconsThemedIcons.Yaml&gt;()        // Icon image for rendering</code>
    ///</example>
    [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
    public sealed class FileYaml : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
    {

      /// <inheritdoc cref="FileYaml">identifier class</inheritdoc>
      public static global::JetBrains.UI.Icons.IconId Id =
        new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(FileYaml));

      /// <summary>Loads the image for Themed Icon Yaml theme aspect Color.</summary>
      public global::JetBrains.Util.Icons.TiImage Load_Color()
      {
        return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
          "<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
          "/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M0,0L16,0L16,1" +
          "6L0,16Z\' fill=\'#FFFFFF\' opacity=\'0\'/><linearGradient id=\'F1\' x1=\'0.4999999999999" +
          "9994\' y1=\'0\' x2=\'0.49999999999999994\' y2=\'1.0000000000000002\'><stop offset=\'0\' s" +
          "top-color=\'#5D6C75\'/><stop offset=\'1\' stop-color=\'#304145\'/></linearGradient><pa" +
          "th d=\'M14,7L14,4L11,4L11,1L2,1L2,5L5,5L5,8L8,8L8,14L16,14L16,7L14,7Z\' fill=\'url(" +
          "#F1)\'/><linearGradient id=\'F2\' x1=\'0.49999999999999994\' y1=\'0\' x2=\'0.49999999999" +
          "999994\' y2=\'1\'><stop offset=\'0\' stop-color=\'#69E68F\'/><stop offset=\'1\' stop-colo" +
          "r=\'#00A131\'/></linearGradient><path d=\'M3,2L10,2L10,4L3,4Z\' fill=\'url(#F2)\'/><li" +
          "nearGradient id=\'F3\' x1=\'0.49999999999999989\' y1=\'0\' x2=\'0.49999999999999989\' y2" +
          "=\'1\'><stop offset=\'0\' stop-color=\'#69E68F\'/><stop offset=\'1\' stop-color=\'#00A131" +
          "\'/></linearGradient><path d=\'M6,5L13,5L13,7L6,7Z\' fill=\'url(#F3)\'/><linearGradie" +
          "nt id=\'F4\' x1=\'0.5\' y1=\'0\' x2=\'0.5\' y2=\'1\'><stop offset=\'0\' stop-color=\'#D6F6FF\'" +
          "/><stop offset=\'1\' stop-color=\'#729BB0\'/></linearGradient><path d=\'M9,8L15,8L15," +
          "10L9,10Z\' fill=\'url(#F4)\'/><linearGradient id=\'F5\' x1=\'0.5\' y1=\'0\' x2=\'0.5\' y2=\'" +
          "1\'><stop offset=\'0\' stop-color=\'#D6F6FF\'/><stop offset=\'1\' stop-color=\'#729BB0\'/" +
          "></linearGradient><path d=\'M9,11L15,11L15,13L9,13Z\' fill=\'url(#F5)\'/><linearGrad" +
          "ient id=\'F6\' x1=\'0.49992831541218646\' y1=\'0\' x2=\'0.49992831541218646\' y2=\'1\'><st" +
          "op offset=\'0\' stop-color=\'#853232\'/><stop offset=\'1\' stop-color=\'#570000\'/></lin" +
          "earGradient><path d=\'M4.201,7L3.487,8.496L2.773,7L0,7L0,8.26L2,12.297L2,15L4.975" +
          ",15L4.975,12.297L6.975,8.26L6.975,7L4.201,7Z\' fill=\'url(#F6)\'/><linearGradient i" +
          "d=\'F7\' x1=\'0.5\' y1=\'0\' x2=\'0.5\' y2=\'0.99999999999999978\'><stop offset=\'0\' stop-c" +
          "olor=\'#FF8282\'/><stop offset=\'1\' stop-color=\'#FF5E5E\'/></linearGradient><path d=" +
          "\'M4.832,8L3.487,10.818L2.143,8L0.987,8L2.854,11.769L2.854,14L4.121,14L4.121,11.7" +
          "69L5.987,8L4.832,8Z\' fill=\'url(#F7)\'/></g></svg>");
      }

      /// <summary>Loads the image for Themed Icon Yaml theme aspect Gray.</summary>
      public global::JetBrains.Util.Icons.TiImage Load_Gray()
      {
        return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
          @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M14,7L14,4L11,4L11,1L2,1L2,5L5,5L5,8L8,8L8,14L16,14L16,7L14,7Z' fill='#F4F4F4'/><path d='M3,2L10,2L10,4L3,4Z' fill='#388A34'/><path d='M6,5L13,5L13,7L6,7Z' fill='#388A34'/><path d='M9,8L15,8L15,10L9,10Z' fill='#323232'/><path d='M9,11L15,11L15,13L9,13Z' fill='#323232'/><path d='M4.201,7L3.487,8.496L2.773,7L0,7L0,8.26L2,12.297L2,15L4.975,15L4.975,12.297L6.975,8.26L6.975,7L4.201,7Z' fill='#F4F4F4'/><path d='M4.832,8L3.487,10.818L2.143,8L0.987,8L2.854,11.769L2.854,14L4.121,14L4.121,11.769L5.987,8L4.832,8Z' fill='#323232'/></g></svg>");
      }

      /// <summary>Loads the image for Themed Icon Yaml theme aspect GrayDark.</summary>
      public global::JetBrains.Util.Icons.TiImage Load_GrayDark()
      {
        return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg(
          @"<svg ti:v='1' width='16' height='16' viewBox='0,0,16,16' xmlns='http://www.w3.org/2000/svg' xmlns:ti='urn:schemas-jetbrains-com:tisvg'><g><path d='M0,0L16,0L16,16L0,16Z' fill='#FFFFFF' opacity='0'/><path d='M14,7L14,4L11,4L11,1L2,1L2,5L5,5L5,8L8,8L8,14L16,14L16,7L14,7Z' fill='#252525'/><path d='M3,2L10,2L10,4L3,4Z' fill='#86D086'/><path d='M6,5L13,5L13,7L6,7Z' fill='#86D086'/><path d='M9,8L15,8L15,10L9,10Z' fill='#C4C4C4'/><path d='M9,11L15,11L15,13L9,13Z' fill='#C4C4C4'/><path d='M4.201,7L3.487,8.496L2.773,7L0,7L0,8.26L2,12.297L2,15L4.975,15L4.975,12.297L6.975,8.26L6.975,7L4.201,7Z' fill='#252525'/><path d='M4.832,8L3.487,10.818L2.143,8L0.987,8L2.854,11.769L2.854,14L4.121,14L4.121,11.769L5.987,8L4.832,8Z' fill='#C4C4C4'/></g></svg>");
      }

      /// <summary>Returns the set of theme images for Themed Icon Yaml.</summary>
      public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
        GetThemeImages()
      {
        return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[]
        {
          new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Color",
            new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
              this.Load_Color)),
          new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Gray",
            new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
              this.Load_Gray)),
          new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage(
            "GrayDark",
            new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(
              this.Load_GrayDark))
        };
      }
    }
    #endregion
  }
}
